- Added GameLiftServer SDK - Added GameLift Server Code to GameModeServerBase Class - Added GameLiftExampleServer.Target.cs, so we can build a dedicated server executable - Added "bForceEnableExceptions = true;" to GameLiftExample.Target.cs  to supress build error C4577 - Added "bForceEnableExceptions = true;" to GameLiftExampleServer.Target.cs  to supress build error C4577 - Changed Project Settings